CegWeboldal/CegWeboldal/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace CegWeboldal.Models
{
    public partial class Employee
    {
        [Required]
        [Display(Name = "Employee id: ")]
        public decimal Empid { get; set; }

        [Required]
        [Display(Name = "First name: ")]
        public string Fname { get; set; }

        [Required]
        [Display(Name = "Last name: ")]
        public string Sname { get; set; }

        [Display(Name = "Manager: ")]
        public decimal? Manager { get; set; }

        [Required]
        [Display(Name = "Post: ") ]
        public string Post { get; set; }
        public string Picture { get; set; }
        public string Cv { get; set; }
        [Display(Name = "Password")]
        public string Emppassword { get; set; }
        public string Username { get; set; }

    }
}

CegWeboldal/CegWeboldal/Models/EmployeeListViewModel.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CegWeboldal.Models
{
    public class EmployeeListViewModel
    {
        public List<Employee> Employees { get; set; }
        public Employee EditedEmployee { get; set; }
    }
}

CegWeboldal/CegWeboldal/Models/ErrorViewModel.cs
using System;

namespace CegWeboldal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CegWeboldal/CegWeboldal/Models/MapperFactory.cs
using AutoMapper;

namespace CegWeboldal.Models
{

    public class MapperFactory
    {
        public static IMapper CreateMapper()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Data.Employee, Models.Employee>()
                .ForMember(dest => dest.Empid, map => map.MapFrom(src => src.Empid))
                .ForMember(dest => dest.Fname, map => map.MapFrom(src => src.Fname))
                .ForMember(dest => dest.Sname, map => map.MapFrom(src => src.Sname))
                .ForMember(dest => dest.Manager, map => map.MapFrom(src => src.Manager))
                .ForMember(dest => dest.Post, map => map.MapFrom(src => src.Post))
                .ForMember(dest => dest.Picture, map => map.MapFrom(src => src.Picture))
                .ForMember(dest => dest.Cv, map => map.MapFrom(src => src.Cv))
                .ForMember(dest => dest.Emppassword, map => map.MapFrom(src => src.Emppassword))
                .ForMember(dest => dest.Username, map => map.MapFrom(src => src.Username))
                /*.ReverseMap()*/;
            });

            return config.CreateMapper();
        }
    }
}

CegWeboldal/CegWeboldal/Controllers/EmployeesController.cs
using AutoMapper;
using CegWeboldal.Logic;
using CegWeboldal.Models;
using Microsoft.AspNetCore.Mvc;
using MySqlX.XDevAPI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CegWeboldal.Controllers
{
    public class EmployeesController : Controller
    {
        private ICrudFunctions crudFunctions;
        private ILoginLogic loginLogic;
        private IMapper mapper;
        private EmployeeListViewModel vm;

        public EmployeesController(ICrudFunctions crudFunctions, ILoginLogic loginLogic, IMapper mapper)
        {
            this.crudFunctions = crudFunctions;
            this.loginLogic = loginLogic;
            this.mapper = mapper;
            this.vm = new EmployeeListViewModel();
            this.vm.EditedEmployee = new Models.Employee();
            var employees = this.crudFunctions.GetAllEmployees();
            this.vm.Employees = this.mapper.Map<IList<Data.Employee>, List<Models.Employee>>(employees);
        }

        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("EmployeesIndex", this.vm);
        }

        public IActionResult Details(decimal id)
        {
            return this.View("EmployeesDetails", this.GetEmployeeModel(id));
        }

        [HttpPost]
        public IActionResult Edit(Models.Employee employee, string editAction)
        {
            if (this.ModelState.IsValid && employee != null)
            {
                this.TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    try
                    {
                        this.crudFunctions.InsertEmployee(employee.Fname, employee.Sname, employee.Post);
                    }
                    catch (ArgumentException ex)
                    {
                        this.TempData["editResult"] = "AddEmployee FAIL: " + ex.Message;
                    }
                }
                else
                {
                    this.crudFunctions.UpdateEmployee(employee.Empid, employee.Cv, employee.Fname, employee.Sname, employee.Post, employee.Picture);
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.vm.EditedEmployee = employee;
                return this.View("EmployeesIndex", this.vm);
            }
        }

        public IActionResult Remove(decimal id)
        {
            this.TempData["editResult"] = "Delete OK";
            this.crudFunctions.RemoveEmployee(id);
            return this.RedirectToAction(nameof(this.Index));
        }

        public IActionResult Edit(decimal id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditedEmployee = this.GetEmployeeModel(id);
            return this.View("EmployeesIndex", this.vm);
        }

        [HttpPost]
        public IActionResult Login()
        {
            if (loginLogic.LoginCheck(this.Request.Form.ToList()[0].Value, this.Request.Form.ToList()[1].Value))
            {
                return this.View("EmployeesDetails", this.GetEmployeeModel(1));
            }
            return this.RedirectToAction(nameof(this.Index));
        }

        private Models.Employee GetEmployeeModel(decimal id)
        {
            Data.Employee oneEmployee = this.crudFunctions.GetEmployeeById(id);
            return this.mapper.Map<Data.Employee, Models.Employee>(oneEmployee);
        }
    }
}

CegWeboldal/CegWeboldal/Controllers/HomeController.cs
using CegWeboldal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CegWeboldal.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CegWeboldal/CegWeboldal/Views/Employees/EmployeesDetails.cshtml
@model CegWeboldal.Models.Employee

@{
    ViewData["Title"] = "EmployeesDetails";
}

<h2> Datasheet of an employee </h2>
    
@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Fname)</td>
        <td>@Html.DisplayFor(m => m.Fname)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Sname)</td>
        <td>@Html.DisplayFor(m => m.Sname)</td>
    </tr>
</table>

CegWeboldal/CegWeboldal/Views/Employees/EmployeesEdit.cshtml
@model CegWeboldal.Models.Employee

<h2>EmployeesEdit</h2>

@using (Html.BeginForm("Edit", "Employees"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Empid)
    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Fname)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Fname)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Sname)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Sname)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Post)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Post)</div>
}
<br>
<input type="file" id="myFile" name="filename"/>
<br>
<br>
<input type="submit" value="SAVE CHANGES" />

CegWeboldal/CegWeboldal/Views/Employees/EmployeesIndex.cshtml
@model CegWeboldal.Models.EmployeeListViewModel

@{
    ViewData["Title"] = "EmployeesIndex";
}

<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("EmployeesLogin", Model.EditedEmployee)

@await Html.PartialAsync("EmployeesList", Model.Employees)

CegWeboldal/CegWeboldal/Views/Employees/EmployeesList.cshtml
@model IEnumerable<CegWeboldal.Models.Employee>

<h2>EmployeesList</h2>
@if (Model.Count() == 0)
{
    <p>No data in the databse!</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Fname)</th>
            <th>@Html.DisplayNameFor(m => m.First().Sname)</th>
            <th>@Html.DisplayNameFor(m => m.First().Post)</th>
            <th>@Html.DisplayNameFor(m => m.First().Picture)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Modify</th>
        </tr>

        @foreach (var employee in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => employee.Fname)</td>
                <td>@Html.DisplayFor(m => employee.Sname)</td>
                <td>@Html.DisplayFor(m => employee.Post)</td>
                <td>@Html.DisplayFor(m => employee.Picture)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = employee.Empid })</td>
                <td>@Html.ActionLink("[DELL]", "Remove", new { id = employee.Empid })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = employee.Empid })</td>
            </tr>
        }
    </table>
}

CegWeboldal/CegWeboldal/Views/Employees/EmployeesLogin.cshtml
@model CegWeboldal.Models.Employee

<h2>EmployeesLogin</h2>

@*@using (Html.BeginForm("Login", "Employees"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Empid)

    <div class="label-field">@Html.LabelFor(m => m.Username)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Username)</div>
    <div class="label-field">@Html.LabelFor(m => m.Emppassword)</div>
    <div class="password-field">@Html.PasswordFor(m => m.Emppassword)</div>
}*@

@using (Html.BeginForm("Login", "Employees"))
{
    <div class="container">
        <label for="uname"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="uname" required>
        <br>
        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="psw" required>
        <br>
        <button type="submit">Login</button>
    </div>
}

CegWeboldal/CegWeboldal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to our firm</h1>
    <p>Please click the link to view our list of employees.</p>
</div>

<a href="/employees">View employees</a>

CegWeboldal/CegWeboldal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CegWeboldal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CegWeboldal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CegWeboldal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>